### ISSUE TITLE
Property Care V1 Manual

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#1021]
- [x] **Add text to https://www.domits.com/hostdashboard/property-care:**
Are you looking for a cleaner, housekeeper or maintenance handyman? Our partner [Mostpros](https://www.mostpros.com/nl/) has a network of home service professionals ready to support you. [Send us a message here](https://www.domits.com/contact) and we connect you with them.

**Comment by chantbalci** [comment]
property is also now in production V1 and its now a simple refrence
