### ISSUE TITLE
Stripe account connection: check the code if stripe is properly connected with domits 

### ISSUE THREAD

**Issue by chantbalci** [domits1/Domits#1045]
The pop-up (you need a stripe account to receive payments) still appears stating that you need a Stripe account, even though you’ve already created one. check the code and fix this issue.

![image](https://github.com/user-attachments/assets/11bb3444-db44-4da1-9224-9c38d1bfac41)

**Comment by Chanlyj** [comment]
Related Issue
[ ] Issue #1054

**Comment by chantbalci** [comment]
Me and Justin managed to fix the issue. We first debugged to find out the problem (core of the problem), afterward we contacted a developer of stripe. after the contact they provided us more info about how the API is structured and also gave specific link references to how we could solve the problem. We also made a manual API to delete existing users that are deleted from within the stripe express platform (this is because some of the users have created multiple account with the same email, and this was because of the bug, but they still exists).
