### ISSUE TITLE
Web: Medium fix: header responsiveness

### ISSUE THREAD

**Issue by Timmhart** [domits1/Domits#1116]
**Is your feature request related to a problem? Please describe.**
Responsiveness header.

**Describe the solution you'd like**
Mobile view needs to be the same as the app navigation. 3 tabs at the bottom from left to right: Home | Messages | Profile

**Additional context**
### Current:
<img src="https://github.com/user-attachments/assets/65835b91-82b9-4e36-862f-f13841014642" width="300">

### Expected: (Don't mind the map view button)
<img src="https://github.com/user-attachments/assets/40ed126f-3b24-484a-b308-8d63da7df160" width="300">

Please make sure you can still open the drop down, or in this case drop up after pressing the profile icon!

**Comment by Muubii** [comment]
![image](https://github.com/user-attachments/assets/1e8ed115-2922-434d-9b59-e85eefc9ebee)
fix icons
