### ISSUE TITLE
Web: Host dashboard: Listings tab - slideshow bug

### ISSUE THREAD

**Issue by Timmhart** [domits1/Domits#1195]
**Is there an existing issue for this?**
- [x] no

**Describe the bug**
In the host dashboard under the listing tab you see a slideshow of the images. But there is a bug with duplicate images (see video below). I don't want a slideshow here.

**Expected behavior**
I just want to see the image here which is also on the homepage, no slideshow.

**To Reproduce**
0. clone, install, serve app locally

**Logs, Screenshots, Video**

https://github.com/user-attachments/assets/de9812d1-a43f-484e-b4c7-ba1161a17d67

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chanlyj** [comment]
The bug with the slideshow not showing images is now fixed.

https://github.com/user-attachments/assets/c49e1a1f-24a9-4a0a-bbf0-8f392770de7b
