### ISSUE TITLE
Website: v1 Availability Management calendar for hosts (sellers)

### ISSUE THREAD

**Issue by Timmhart** [domits1/Domits#174]
Booking calendar for guests (buyers)
Availability management calendar for hosts (sellers)
Support for different time zones
Handle Daylight Savings changes etc.
Stock management
Seats
Ability to filter search by availability

**Comment by stefanhopman1** [comment]
Old:

Don't mind the rest of the design yet. First make sure the calendar works.

This is a calendar in the host dashboard. Here the host can pick dates when the accommodation is or is not available for rental.
![Host Calendar](https://github.com/domits1/Domits/assets/63649558/926dde10-ced9-45aa-9f58-efb254f66b91)

On the traveller side a calendar is needed for booking the accommodation. This will happen on the accommodation detailpage, see image below:
![Scherm­afbeelding 2024-02-02 om 08 57 29](https://github.com/domits1/Domits/assets/63649558/848d8342-2f42-4ed6-a766-a01609de2983)
The traveller needs to pick a check-in date and a check-out date. Below is an image when both are clicked:
