### ISSUE TITLE
change request for meta title & description

### ISSUE THREAD

**Issue by roberthopman** [domits1/Domits#431]
expected: @stefanhopman1 / @Timmhart can you share what the title and description should be?

actual: 'react app' and 'website created using ....'
source: linkedin
<img width="562" alt="Screenshot 2024-03-28 at 17 22 32" src="https://github.com/domits1/Domits/assets/3865531/2c893145-5167-436b-821a-583d7af6d3d1">

**Comment by Timmhart** [comment]
Meta title is: Domits - Holiday rentals, campers, boats and more...
Will have to look where 'React app' and 'website created using ....' is coming from.

**Comment by Timmhart** [comment]
Found the issue. The meta title and description aren't changed correctly

**Comment by Timmhart** [comment]
@SHvanderWilt can you please correct these meta tags:

<meta name="description" content="Web site created using create-react-app"/>
to 
<meta name="description" content="- Holiday rentals, campers, boats and more..."/>
