### ISSUE TITLE
Research & Presentation Search 

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#687]
Research & Presentation for Web/App Search Guest/Host 
Date: ...
Presentation: https://docs.google.com/presentation/d/19fJ6DWoYf4H3wBnC2eg077zcRIwVtojIajsVnFv76Hk/

Definition Search planning strategy
Search strategy elements
Domits current Search strategy
Domits future Search strategy
How we will implement this step-by-step
Other things to keep in mind...

**Comment by kacperfl** [comment]
Datum voor de presentatie is 21 Mei.
