### ISSUE TITLE
Payments knop in de host dashboard werkt momenteel niet.

### ISSUE THREAD

**Issue by TimSeijlhouwer** [domits1/Domits#690]
Als je op de payments knop in de host dashboard drukt gebeurt er nu niks. in de developer console krijg ik deze error.  Error: HTTP error! Status: 500
    at onClick (Pages.js:62:17)
zuak8serw5.execute-api.eu-north-1.amazonaws.com/dev/CreateStripeAccount:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()

**Comment by MC38-03** [comment]
Gefixt
