### ISSUE TITLE
Duidelijkere foutmelding als er geen resultaten zijn binnen de searchbar

### ISSUE THREAD

**Issue by TimSeijlhouwer** [domits1/Domits#691]
Als er nu geen accommodaties beschikbaar zijn binnen de search krijg je in het hoekje links in de searchbar een erg kleine foumelding. Dit is erg onduidelijk. (Kacper heeft hier wel al aan gewerkt alleen liep hier een beetje vast).

**Comment by kacperfl** [comment]
De nieuwe alert is er toegevoegd als een tijdelijke oplossing
