### ISSUE TITLE
Web - Privacy policy

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#737]
V2: https://docs.google.com/document/d/1YezDanQPwvK1ZxGt2YnWIpzC6qkCQbnTN9qZ7BtLloU/

**Comment by vanheerwaardenchiel-bit** [comment]
<img width="1482" height="2921" alt="Image" src="https://github.com/user-attachments/assets/bb81a2d3-526e-4326-a4a7-890ea7bca10e" />
