### ISSUE TITLE
Web - Terms and conditions

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#738]
v2: https://docs.google.com/document/d/1vY-bn7dOx34ve72DR826tH7h5NeU3xjcuua-Kk4OK0I/

**Comment by vanheerwaardenchiel-bit** [comment]
<img width="1482" height="3456" alt="Image" src="https://github.com/user-attachments/assets/705b4c48-aeb7-498d-bdcc-9892a691cbd6" />
