### ISSUE TITLE
Step 10: Host Onboarding v2: Listing Rate

### ISSUE THREAD

**Issue by stefanhopman1** [domits1/Domits#785]
https://www.figma.com/design/CTGbCIqZXdLBKgZCwo9XXE/Domits-Screens?node-id=4416%3A29130&t=g49DPp9DlWLjXVXH-1

**Comment by stefanhopman1** [comment]
v3 done

**Comment by vanheerwaardenchiel-bit** [comment]
<img width="1452" height="1873" alt="Image" src="https://github.com/user-attachments/assets/381ae94c-db34-4cc9-942b-9d31fafaf4a5" />
