### ISSUE TITLE
Je kan als binnen de host of guest dashboard bent niet de search gebruiken. Als je voorwaarden invult gebeurt er niks als je op de zoek knop drukt

### ISSUE THREAD

**Issue by TimSeijlhouwer** [domits1/Domits#800]
**Is there an existing issue for this?**
- [ ] no

**Describe the bug**

**Expected behavior**

**To Reproduce**
0. clone, install, serve app locally

**Logs, Screenshots, Video**
If applicable, add information, like logs, screenshots, video to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kacperfl** [comment]
De probleem is opgelost door te checken of er een / is Domits.com ,acceptance.Domits.com, localhost:3000 zijn allemaal homepages door te checken of er een / weet je of je op en andere pagina bent. Door gebruik te maken van useLocation en useNavigate kan je dat mogelijk maken.

Daarnaast als je op een andere pagina bent en je voert de opdracht uit en je probeer wat te zoeken worden de resultaten meteen uitgevoerd door de useEffect hook setSearchResults meteen aan te roepen zodra je op de homepage bent. setSearchResults is de functie dat filtering regeld voor de accommodaties.
