### ISSUE TITLE
Skeleton loader werkt niet als vanaf een pagina terug gaat naar de home pagina

### ISSUE THREAD

**Issue by TimSeijlhouwer** [domits1/Domits#958]
**Is there an existing issue for this?**
- [ ] no
Als je naar een andere pagina gaat bijvoorbeeld de faq, en dan links boven op terug drukt de home pagina niet laadt.

**Expected behavior**
Als je vanaf een andere pagina terug gaat naar de home pagina moet deze laden alsof je de pagina herlaadt.

**To Reproduce**
0. clone, install, serve app locally

**Logs, Screenshots, Video**
If applicable, add information, like logs, screenshots, video to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kacperfl** [comment]
fixed: https://github.com/domits1/Domits/pull/960
